### get Transactions
GET http://localhost:3333/transactions

### Create a new transaction
POST http://localhost:3333/transactions
Content-Type: application/json

{
  "title":"frelancer 01",
  "type":"credit",
  "amount":100
}
