@cookie = sessionId=79db6e73-eaf1-4af8-9ccc-d36d9d6688ec; Max-Age=604800000; Path=/; SameSite=Lax

### Get Transactions
// @no-cookie-jar   remove cookie
GET http://localhost:3333/transactions
Cookie: {{cookie}}

### Get Transactions by ID
// @no-cookie-jar 
GET http://localhost:3333/transactions/57f1bdc1-bdd7-4385-8ef8-83fc8d321e67
Cookie: {{cookie}}

### Create a new transaction
// @no-cookie-jar 
POST http://localhost:3333/transactions
Content-Type: application/json
Cookie: {{cookie}}

{
  "title":"frelancer 03",
  "type":"credit",
  "amount":3000
}

### Get summary
// @no-cookie-jar 
GET http://localhost:3333/transactions/summary
Cookie: {{cookie}}

